Zuul gateway
leafchild0/auth-buddy pull request #12
Opened 2020-03-23 13:26 UTC by RVRhub

Add zuul gateway service
Add new data service
Add security for zuul gateway

2020-03-23 17:05 UTC, leafchild0 requested changes

2020-03-23 17:05 UTC, leafchild0 commented on auth-service/src/main/java/com/poc/authserver/security/SecurityConfig.java
> +//			.addFilterAfter(new JwtUsernamePasswordAuthenticationFilter(authenticationManager()),
This can be removed?

2020-03-23 17:05 UTC, leafchild0 commented on gateway-service/src/main/java/com.poc.gateway/SecurityConfig.java
> +//			.antMatchers("/data/admin").hasRole("ADMIN")
Please remove that if this is not needed. Better add comments if you want to show something

2020-03-23 17:06 UTC, RVRhub commented on auth-service/src/main/java/com/poc/authserver/security/SecurityConfig.java
> +//			.addFilterAfter(new JwtUsernamePasswordAuthenticationFilter(authenticationManager()),
Yes, it can be

2020-03-23 17:08 UTC, RVRhub commented on gateway-service/src/main/java/com.poc.gateway/SecurityConfig.java
> +//			.antMatchers("/data/admin").hasRole("ADMIN")
Next task I plan to add role support

2020-03-23 20:32 UTC, leafchild0 commented on auth-service/src/main/java/com/poc/authserver/security/SecurityConfig.java
> +//			.addFilterAfter(new JwtUsernamePasswordAuthenticationFilter(authenticationManager()),
Waiting....

2020-03-24 08:53 UTC, leafchild0 approved these changes

2020-03-24 08:53 UTC, merged